version: 2.1

orbs:
  aws-cli: circleci/aws-cli@1.3.1
  slack: circleci/slack@3.4.2

jobs:
  run-tests:
    docker:
      - image: circleci/python:3.8.3
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      - run:
          name: Run Tests
          command: |
            pytest src
  build-and-deploy:
    docker:
      - image: cimg/node:16.5
    steps:
      - checkout
      - aws-cli/setup:
          aws-region: AWS_DEFAULT_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - run:
          name: Install architect
          command: |
            npm i @architect/architect
            npx arc init
            echo @env\n >> preferences.arc
            echo production\n >> preferences.arc
            echo SLACK_OAUTH_ACCESS_TOKEN ${SLACK_OAUTH_ACCESS_TOKEN}\n >> preferences.arc
            echo SLACK_SIGNING_SECRET ${SLACK_SIGNING_SECRET}\n >> preferences.arc
            npx arc env production ARC_APP_SECRET ${ARC_APP_SECRET}
            npx arc env production SLACK_OAUTH_ACCESS_TOKEN ${SLACK_OAUTH_ACCESS_TOKEN}
            npx arc env production SLACK_SIGNING_SECRET ${SLACK_SIGNING_SECRET}
      - run:
          name: Deploy
          command: |
            npx arc deploy production

workflows:
  version: 2
  build:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only:
                - master
      - run-tests
